server:
  port: 8081
  servlet:
    context-path: /sell
spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  pattern:
    console: "%d - %msg%n"
  file:
    path: D://JavaWorkPlace/var/log/tomcat/sell.log
  level:
    com.zzz.sell.LoggerTest: debug
